
# Generated by ChatGPT on 2025-11-11
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Системное имя')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название (для админки)')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Текст')),
                ('named_url', models.CharField(blank=True, help_text='Например: home. Без аргументов.', max_length=200, verbose_name='Имя URL (reverse)')),
                ('url', models.CharField(blank=True, help_text='Абсолютный или относительный путь.', max_length=255, verbose_name='URL (если без имени)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu', verbose_name='Меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menuitem', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['parent__id', 'order', 'title'],
            },
        ),
    ]
